server:
  port: 8080
  servlet:
    context-path: /identity

management:
  endpoints:
    web:
      exposure:
        include=*:

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root

  #  security:
  #    user:
  #      name: root
  #      password: root

  #config show banner
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    signerkey: "XWl33AU6HWMautGS26y9CbGCIigErNizJnufWoFGEjvjUaIJBjmen2ggppRMM8Hy"
    valid-duration: 3600 #in second (han cua token)
    refreshable-duration: 36000 #in seconds

  main:
    banner-mode: off
# Config logging ( debug -> info -> warn -> error -> fatle)
# logging:
#  level:
#    root: WARN