server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: admin
#  security:
#    user:
#      name: none
#      password: none

  #config show banner
  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Config logging ( debug -> info -> warn -> error -> fatle)
# logging:
#  level:
#    root: WARN