server:
  port: 8080
  servlet:
    context-path: /identity

management:
  endpoints:
    web:
      exposure:
        include=*:
          
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: admin

  #  security:
  #    user:
  #      name: root
  #      password: root

  #config show banner
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    signerkey: "XWl33AU6HWMautGS26y9CbGCIigErNizJnufWoFGEjvjUaIJBjmen2ggppRMM8Hy"

  main:
    banner-mode: off
# Config logging ( debug -> info -> warn -> error -> fatle)
# logging:
#  level:
#    root: WARN